services:
  - docker

stages:
  - name: Unit Tests
    if: branch = master OR branch = develop
  - name: Deploy
    if: branch = master

jobs:
  include:
    - stage: Unit Tests
      language: python
      python:
        - "3.8"
      cache: pip
      install:
        - pip install -r requirements.txt
      script:
        - python -m unittest discover test -p '*_test.py'

    - stage: Deploy
      name: Deploy to Docker hub
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker buildx build -f Dockerfile-plc2-pressure --platform linux/arm/v7 -t $DOCKER_USERNAME/python-test:v6 --push .