sudo: required

services:
  - docker

stages:
  - name: Unit Tests
    if: branch = master OR branch = develop

jobs:
  include:
    - stage: Unit Tests
      before_install:
        - docker build -f Dockerfile-tests -t pythontestapp .
        - docker run -d --name app pythontestapp sleep infinity
        - docker ps -a
      script:
        - docker exec app python -m unittest discover test -p '*_test.py' -s test -v
      
      after_script:
        -docker rm -f app