#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

FROM python:3.8
USER root
# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

COPY . app
WORKDIR app


RUN pip --disable-pip-version-check --no-cache-dir install ddt \
&& pip --disable-pip-version-check --no-cache-dir install nose

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=dialog

