version: '3.1'

services:

    pythonapp:
        image: jonev/python-test:v6
        depends_on:
            - mongo

    mongo:
        image: webhippie/mongodb
        ports:
        - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: malaslt/mongo-express-arm
        ports:
            - 8888:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example