version: '3.1'

services:

    mqtttomysql:
        image: jonev/ba-wago:mysqldatastore-amd64
        depends_on: 
            - db

    simulation:
        image: jonev/ba-wago:simulation-amd64

    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
        depends_on: 
            - db
    
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: example
    adminer:
        image: adminer
        ports:
            - 8080:8080
        depends_on: 
            - db