version: '3.1'

services:

    pythonapp:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ..:/workspace
        command: sleep infinity

    grafana:
        image: jonev/grafana-with-plugins
        ports:
            - 3000:3000
    
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: example
    adminer:
        image: adminer
        ports:
            - 8080:8080