FROM grafana/grafana:6.7.1-ubuntu
USER root
COPY grafana.ini /etc/grafana/grafana.ini
RUN  apt-get update \
    && apt-get -y install git \
    && cd /var/lib/grafana/plugins/ \
    && git clone https://github.com/AutohomeCorp/grafana-compare-queries.git \
    && grafana-cli plugins install marcuscalidus-svg-panel