{
 "title": "Lekkasjedeteksjon_v3.0",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Informasjon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "content": "\n# Informasjon\n\nDashbord og brukermanual utviklet i forbindelse med bacheloroppgave **\"Styre- og overvåkingsystem for distribusjon av drikkevann\"**.\n\nOppgaven er skrevet av studentene **Johan Haukalid, Jone Vassbø, Markus Raudberget og Peder Ward** fra **NTNU** i sammerbeid med **WAGO Norge AS**.\n\n> Brukermanual for dashbordet \"Lekkasjedeteksjon\": https://drive.google.com/open?id=15-gmzFDheQc1qlsgD1KaZ4ck4yzGNBKT.\n",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  id\nFROM LeakDetection120SamplesHourlyAverage\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  { "title": "Oversiktsbilde", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Distribusjonsnettverk",
   "type": "text",
   "description": "Oversiktsbilde over distribusjonsnettverket. Tallet inn i sonene viser antall beboere i sonen. FTxx er strømningsmålere og WPxx er vannrør. FT07 er strømningsmåler ut fra vassverket.",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 8 },
   "content": "<img src=\"https://svgshare.com/i/JXN.svg\" />\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  id\nFROM LeakDetection120SamplesHourlyAverage\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Status",
   "type": "alertlist",
   "description": "Tabellen viser status for hver sone og rør.",
   "gridPos": { "h": 11, "w": 6, "x": 8, "y": 8 },
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Antall avvik siste dag.",
   "type": "gauge",
   "description": "Antall avvik over avviksgrense på 10% siste 24 timene. ",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  pointsOver10 as value,\n  'Antall avvik sone 1' as metric\nFROM LeakDetectionAlarmPoints\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT01_Pv'\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  pointsOver10 as value,\n  'Antall avvik sone 2' as metric\nFROM LeakDetectionAlarmPoints\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT02_Pv'\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  pointsOver10 as value,\n  'Antall avvik sone 3' as metric\nFROM LeakDetectionAlarmPoints\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT03_Pv'\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  pointsOver10 as value,\n  'Antall avvik sone 4' as metric\nFROM LeakDetectionAlarmPoints\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT04_Pv'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Soneoversikt forbruk.",
   "type": "stat",
   "description": "Diagrammet viser nåverdien for forbruket til hver sone.",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  Output_Pv as value,\n  'Sone 1' as metric\nFROM SignalAnalogHmiPv\nWHERE\n   $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT01_Pv'\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  Output_Pv as value,\n  'Sone 2' as metric\nFROM SignalAnalogHmiPv\nWHERE\n   $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT02_Pv'\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  Output_Pv as value,\n  'Sone 3' as metric\nFROM SignalAnalogHmiPv\nWHERE\n   $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT03_Pv'\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  Output_Pv as value,\n  'Sone 4' as metric\nFROM SignalAnalogHmiPv\nWHERE\n   $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT04_Pv'\nORDER BY timestamp"
    }
   ]
  },
  { "title": "Alarmlogg", "type": "alertlist", "gridPos": { "h": 5, "w": 6, "x": 8, "y": 19 } },
  {
   "title": "FT07 Nåverdi",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 21 },
   "format": "litre",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT07' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT07_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "FT07 Total",
   "type": "singlestat",
   "description": "Total mengde ut fra vassverk siste 24 timer.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 21 },
   "format": "l/s",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT07' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT07_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "FT07 Maks",
   "type": "singlestat",
   "description": "Maksverdi ut fra vassverk siste 24 timer.",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 21 },
   "format": "l/s",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT07' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT07_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "FT07 Min",
   "type": "singlestat",
   "description": "Minimumsverdi ut fra vassverk siste 24 timer.",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 21 },
   "format": "l/s",
   "valueName": "min",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT07' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT07_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  { "title": "Rør overvåkning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Avvik inn/ut WP05",
   "type": "graph",
   "description": "Grafen viser avviket mellom inn og ut verdi for \"WaterPipe\".",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "l/s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'Avvik inn/ut' as metric\nFROM LeakDetectionBalanceHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'FT05_is_FT03_FT04'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Avvik inn/ut WP06",
   "type": "graph",
   "description": "Grafen viser avviket mellom inn og ut verdi for \"WaterPipe\".",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "l/s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'Avvik inn/ut' as metric\nFROM LeakDetectionBalanceHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'FT06_is_FT02_FT05'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Avvik inn/ut WP07",
   "type": "graph",
   "description": "Grafen viser avviket mellom inn og ut verdi for \"WaterPipe\".",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "l/s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'Avvik inn/ut' as metric\nFROM LeakDetectionBalanceHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'FT07_is_FT01_FT06'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Rørovervåkning",
   "type": "bargauge",
   "description": "Grafen viser avviket mellom inn og ut verdi for \"WaterPipe\".",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'Avvik inn/ut WP05' as metric\nFROM LeakDetectionBalanceHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'FT05_is_FT03_FT04'\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'Avvik inn/ut WP06' as metric\nFROM LeakDetectionBalanceHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'FT06_is_FT02_FT05'\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'Avvik inn/ut WP07' as metric\nFROM LeakDetectionBalanceHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'FT07_is_FT01_FT06'\nORDER BY timestamp"
    }
   ]
  },
  { "title": "Sone 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Nåverdi",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 36 },
   "format": "litre",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT01' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT01_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "description": "Total mengde siste 24 timer",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 36 },
   "format": "l/s",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT01' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT01_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Dagens og gjennomsnittlig timesverdier",
   "type": "graph",
   "description": "Diagrammet viser dagens gjennomsnittlige timesverdier og de fem siste dagene gjennomsnittlige timesverdier.",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 36 },
   "yaxes": [
    { "format": "l/s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'Dagens timesverdier' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT01_Pv'\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'Gjennomsnittlige timesverdier' as metric\nFROM LeakDetection120SamplesHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT01_Pv'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Antall avvik siste 24 timer.",
   "type": "graph",
   "description": "Antall avvik over avviksgrense på 10% siste 24 timene. ",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  pointsOver10 as value,\n  'Antall avvik' as metric\nFROM LeakDetectionAlarmPoints\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT01_Pv'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Maks",
   "type": "singlestat",
   "description": "Maksverdi siste 24 timer",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 39 },
   "format": "l/s",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT01' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT01_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Min",
   "type": "singlestat",
   "description": "Minimumverdi siste 24 timer",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 39 },
   "format": "l/s",
   "valueName": "min",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT01' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT01_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Antall avvik siste 24 timer.",
   "type": "gauge",
   "description": "Antall avvik over avviksgrense på 10% siste 24 timene. ",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  pointsOver10 as value,\n  'Antall avvik sone 1' as metric\nFROM LeakDetectionAlarmPoints\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT01_Pv'\nORDER BY timestamp"
    }
   ]
  },
  { "title": "Sone 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Nåverdi",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 47 },
   "format": "litre",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT02' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT02_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "description": "Total mengde siste 24 timer",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 47 },
   "format": "l/s",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT02' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT02_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Dagens og gjennomsnittlig timesverdier.",
   "type": "graph",
   "description": "Diagrammet viser dagens gjennomsnittlige timesverdier og de fem siste dagene gjennomsnittlige timesverdier.",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 47 },
   "yaxes": [
    { "format": "l/s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'Dagens timesverdier' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT02_Pv'\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'Gjennomsnittlige timesverdier' as metric\nFROM LeakDetection120SamplesHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT02_Pv'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Antall avvik siste 24 timer.",
   "type": "graph",
   "description": "Antall avvik over avviksgrense på 10% siste 24 timene. ",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  pointsOver10 as value,\n  'Antall avvik' as metric\nFROM LeakDetectionAlarmPoints\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT02_Pv'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Maks",
   "type": "singlestat",
   "description": "Maksverdi siste 24 timer",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 50 },
   "format": "l/s",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT02' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT02_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Min",
   "type": "singlestat",
   "description": "Minimumverdi siste 24 timer",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 50 },
   "format": "l/s",
   "valueName": "min",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT02' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT02_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Antall avvik siste 24 timer.",
   "type": "gauge",
   "description": "Antall avvik over avviksgrense på 10% siste 24 timene. ",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  pointsOver10 as value,\n  'Antall avvik sone 2' as metric\nFROM LeakDetectionAlarmPoints\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT02_Pv'\nORDER BY timestamp"
    }
   ]
  },
  { "title": "Sone 3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Nåverdi",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 58 },
   "format": "litre",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT03' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT03_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "description": "Total mengde siste 24 timer",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 58 },
   "format": "l/s",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT03' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT03_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Dagens og gjennomsnittlig timesverdier.",
   "type": "graph",
   "description": "Diagrammet viser dagens gjennomsnittlige timesverdier og de fem siste dagene gjennomsnittlige timesverdier.",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 58 },
   "yaxes": [
    { "format": "l/s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'Dagens timesverdier' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT03_Pv'\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'Gjennomsnittlige timesverdier' as metric\nFROM LeakDetection120SamplesHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT03_Pv'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Antall avvik siste 24 timer.",
   "type": "graph",
   "description": "Antall avvik over avviksgrense på 10% siste 24 timene. ",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  pointsOver10 as value,\n  'Antall avvik' as metric\nFROM LeakDetectionAlarmPoints\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT03_Pv'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Maks",
   "type": "singlestat",
   "description": "Maksverdi siste 24 timer",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 61 },
   "format": "l/s",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT03' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT03_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Min",
   "type": "singlestat",
   "description": "Minimumverdi siste 24 timer",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 61 },
   "format": "l/s",
   "valueName": "min",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT03' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT03_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Antall avvik siste 24 timer.",
   "type": "gauge",
   "description": "Antall avvik over avviksgrense på 10% siste 24 timene. ",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  pointsOver10 as value,\n  'Antall avvik sone 3' as metric\nFROM LeakDetectionAlarmPoints\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT03_Pv'\nORDER BY timestamp"
    }
   ]
  },
  { "title": "Sone 4", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Nåverdi",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 69 },
   "format": "litre",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT04' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT04_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "description": "Total mengde siste 24 timer",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 69 },
   "format": "l/s",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT04' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT04_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Dagens og gjennomsnittlig timesverdier.",
   "type": "graph",
   "description": "Diagrammet viser dagens gjennomsnittlige timesverdier og de fem siste dagene gjennomsnittlige timesverdier.",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 69 },
   "yaxes": [
    { "format": "l/s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'Dagens timesverdier' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT04_Pv'\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'Gjennomsnittlige timesverdier' as metric\nFROM LeakDetection120SamplesHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT04_Pv'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Antall avvik siste 24 timer.",
   "type": "graph",
   "description": "Antall avvik over avviksgrense på 10% siste 24 timene. ",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  pointsOver10 as value,\n  'Antall avvik' as metric\nFROM LeakDetectionAlarmPoints\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT04_Pv'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Maks",
   "type": "singlestat",
   "description": "Maksverdi siste 24 timer",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 72 },
   "format": "l/s",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT04' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT04_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Min",
   "type": "singlestat",
   "description": "Minimumverdi siste 24 timer",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 72 },
   "format": "l/s",
   "valueName": "min",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value as value,\n  'FT04' as metric\nFROM LeakDetectionHourlyAverage\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT04_Pv' AND\n  timestamp>NOW() - INTERVAL 1 MINUTE\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Antall avvik siste 24 timer.",
   "type": "gauge",
   "description": "Antall avvik over avviksgrense på 10% siste 24 timene. ",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 75 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  pointsOver10 as value,\n  'Antall avvik sone 4' as metric\nFROM LeakDetectionAlarmPoints\nWHERE\n  $__timeFilter(timestamp) AND\n  _tagId = 'WaterFlowFT04_Pv'\nORDER BY timestamp"
    }
   ]
  }
 ]
}